! *** DO NOT EDIT THIS FILE ***
! This file was generated automatically from b4step2.f using
! the permute.py Python script to permute the array
! indices of the following variables:
! q, aux
! If this file is wrong, edit the parent file (for
! algorithmic errors) or the permute.py script
! (for array permutation errors)

c     ============================================
      subroutine b4step2(maxmx,maxmy,mbc,mx,my,meqn,q,
     &            xlower,ylower,dx,dy,t,dt,maux,aux)
c     ============================================
c
c     # called from claw2 before each call to step2.
c     # use to set time-dependent aux arrays or perform other tasks
c     # which must be done every time step.

c
c     # dummy routine 
c
c     
      implicit double precision (a-h,o-z)
      dimension q(meqn,1-mbc:maxmx+mbc,1-mbc:maxmy+mbc)
      dimension aux(maux,1-mbc:maxmx+mbc,1-mbc:maxmy+mbc)
c
      return
      end

