! *** DO NOT EDIT THIS FILE ***
! This file was generated automatically from copyq2.f using
! the permute.py Python script to permute the array
! indices of the following variables:
! q1, q2
! If this file is wrong, edit the parent file (for
! algorithmic errors) or the permute.py script
! (for array permutation errors)

c
c
c =========================================================
      subroutine copyq2(maxmx,maxmy,meqn,mbc,mx,my,q1,q2)
c =========================================================
c
c     # copy the contents of q1 into q2
c
      implicit double precision (a-h,o-z)
      dimension q1(meqn,1-mbc:maxmx+mbc,1-mbc:maxmy+mbc)
      dimension q2(meqn,1-mbc:maxmx+mbc,1-mbc:maxmy+mbc)
c
c
      do 10 j = 1-mbc, my+mbc
        do 10 i = 1-mbc, mx+mbc
          do 10 m=1,meqn
             q2(m,i,j) = q1(m,i,j)
   10        continue
      return
      end

